service: meli

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  memorySize: 256
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
  stage: local
  environment:
    MELI_URL: ${env:MELI_URL}
  
functions:
  hello:
    handler: dist/src/handlers/index.hello
    events:
      - http:
          method: GET
          path: /hello
          authorizer:
            arn: ${env:COGNITO_ARN}
            scopes:
              - ${env:COGNITO_SCOPES}

  searchproducts:
    handler: dist/src/handlers/index.searchproducts
    events:
      - http:
          method: GET
          path: /products
          request:
            parameters:
              querystrings:
                product: true
          authorizer:
            arn: ${env:COGNITO_ARN}
            scopes:
              - ${env:COGNITO_SCOPES}

custom:
  serverless-offline:
    httpPort: 4200
    websocketPort: 4201
    lambdaPort: 4202
  bundle:
    linting: false

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
