name: Meli workflow

on: ['push', 'pull_request']

jobs:

  envfile:
    runs-on: ubuntu-latest
 
    steps:
    - name: Make env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        MELI_URL: ${{ secrets.MELI_URL }}
        COGNITO_ARN: ${{ secrets.COGNITO_ARN }}
        COGNITO_SCOPES: ${{ secrets.COGNITO_SCOPES }}
        directory: .
        file_name: .env
        fail_on_empty: false

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Lint files
        run: |
          yarn lint

      - name: Run all tests
        run: |
          yarn test
  
  deploy:
    if: github.ref == 'refs/heads/development'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Serverless deploy
        uses: serverless/github-action@v2
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
